swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Simple Store"
  contact:
    email: "tiagocaraujo@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "products"
  description: "Products"
schemes:
- "http"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "List All Products"
      description: ""
      operationId: "listProducts"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success!"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      thumbnail: #TODO Avaliar mudança pra bytes
        type: "string"
        description: "Thumbnail"
      name:
        type: "string"
        description: "Name"
      price:
        type: "number"
        format: "float"
        description: "Price"
      description:
        type: "string"
        description: "Product Description"
      shortDescription:
        type: "string"
        description: "Short Product Description"
