swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Simple Store"
  contact:
    email: "tiagocaraujo@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "product"
  description: "Product"
- name: "cart"
  description: "Cart"
schemes:
- "http"
paths:
  /products:
    get:
      tags:
      - "product"
      summary: "List all products"
      description: ""
      operationId: "listProducts"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success!"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
              
  /carts:
    post:
      tags:
      - "cart"
      summary: "Create a new cart"
      produces:
      - "application/json"
      responses:
        200:
          description: "Cart was created"
          schema:
            $ref: "#/definitions/Cart"
            
  /carts/{cartId}/products:
    post:
      tags:
      - "cart"
      summary: "Insert product into cart" 
      parameters:
      - in: "path"
        name: "cartId"
        type: "string"
        format: "uuid"
        required: true
      - in: "body"
        name: "body"
        description: "Product was added to cart"
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        204:
          description: "Product added successfully"
        404:
          description: "Cart not found"
      
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
      thumbnail: #TODO Avaliar mudança pra bytes
        type: "string"
        description: "Thumbnail"
      name:
        type: "string"
        description: "Name"
      price:
        type: "number"
        format: "float"
        description: "Price"
      description:
        type: "string"
        description: "Product Description"
      shortDescription:
        type: "string"
        description: "Short Product Description"
  Cart:
    type: "object"
    properties:
      id:
        type: "integer"
      products:
        type: "array"
        items:
          $ref: "#/definitions/Product"
